# 모듈 로드

In [1]:
from PIL import Image
import numpy as np

# 이미지 데이터를 Average Hash로 변환하기 --- (※1)

In [4]:
def average_hash(fname, size = 16):
    img = Image.open(fname) # 이미지 데이터 열기---(※2)
    img = img.convert('L') # 그레이스케일로 변환하기 --- (※3)
    img = img.resize((size, size), Image.ANTIALIAS) # 리사이즈하기 --- (※4)
    pixel_data = img.getdata() # 픽셀 데이터 가져오기 --- (※5)
    pixels = np.array(pixel_data) # Numpy 배열로 변환하기 --- (※6)
    pixels = pixels.reshape((size, size)) # 2차원 배열로 변환하기 --- (※7)
    avg = pixels.mean() # 평균 구하기 --- (※8)
    diff = 1 * (pixels > avg) # 평균보다 크면 1, 작으면 0으로 변환하기 --- (※9)
    return diff

# Average Hash 출력하기

In [5]:
ahash = average_hash('tower.jpg')

In [6]:
print(ahash)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [1 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0]
 [1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 0]
 [1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1]]


# 이진 해시로 변환하기 --- (※10)

In [33]:
def np2hash(ahash):
    bhash = []
    for nl in ahash.tolist():
        sl = [str(i) for i in nl]
        s2 = "".join(sl)   # 모든 요소들을 하나로 연결하여 출력 (구분자 없애기)
        i = int(s2, 2) # 이진수를 정수로 변환하기
        #print("정수:",i)
        #print("%02x" % i)
        #print("%04x" % i)
        bhash.append("%04x" % i)
    return "".join(bhash)

In [34]:
print(np2hash(ahash))

000001000180018003c003c003c087e07ff05ff07ff2cffa9ffe3ffe3ffe1fff


# 10진수를 16진수 헥사로 변환 예제

In [26]:
n = 255

h = hex(n)           # 숫자를 헥사 문자열로 변환하여 반환
print(h)              # 출력 결과: 0xff

print("%X" % (n))     # 출력 결과: FF
print("%x" % (n))     # 출력 결과: ff
print("0x%X" % (n))   # 출력 결과: 0xFF


print("%X" % (10))    # 출력 결과: A
print("%02X" % (10))  # 출력 결과: 0A

0xff
FF
ff
0xFF
A
0A
